name: Go

on: [ push, pull_request ]

jobs:

#  Build_App:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Set up Go
#      uses: actions/setup-go@v2
#      with:
#        go-version: 1.17.x
#        
#    - name: Lint
#      run: $GITHUB_WORKSPACE/lint.sh
##     run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0 && export MY_PATH=$(echo $GITHUB_REF | awk -F/ '{print $NF}') && cd $MY_PATH  && golangci-lint run -c $GITHUB_WORKSPACE/.golangci.yml -v
#    - name: Test
#      run : $GITHUB_WORKSPACE/test.sh
##      run:  export MY_PATH=$(echo $GITHUB_REF | awk -F/ '{print $NF}') && cd $MY_PATH  && go test .
#    - name: Build app
#      run : $GITHUB_WORKSPACE/build.sh    
##      run: export MY_PATH=$(echo $GITHUB_REF | awk -F/ '{print $NF}') && cd $MY_PATH  && go build .
  Build_Docker_Image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: .
        # Note: tags has to be all lower-case
        tags: "dm0610/products-api:${GITHUB_REF}-$(date +%s)"
        # build on feature branches, push only on main branch
        push: true
